#### NumPy - Basic Operations

##### Mathematical Operations

In [1]:
import numpy as np

In [2]:
#addition
np.add(45,20)

65

In [3]:
#subtraction
np.subtract(45,23)

22

In [3]:
lst = [20,30,40,50,60]

In [4]:
test1 = lst * 2

In [5]:
test1

[20, 30, 40, 50, 60, 20, 30, 40, 50, 60]

In [6]:
test2 = []


In [7]:
for i in lst:
    test2.append(i*2)

In [8]:
test2

[40, 60, 80, 100, 120]

In [9]:
# ndarray multiplication
# create ndarray which conntains number of hrs worked for 5 days
# hourly rate is 15 USD
np_daily_wage = np.array([7,9,13,8,11])*10

In [17]:
np_daily_wage

array([ 70,  90, 130,  80, 110])

In [18]:
#total earning after 5 days
#use sum method to add all data elements of ndarray
sum(np_daily_wage)

480

In [19]:
#print hourly wage for each day
print (np_daily_wage)

[ 70  90 130  80 110]


In [20]:
np_daily_wage

array([ 70,  90, 130,  80, 110])

##### Comparison Operations

In [21]:
#comparison operations
#create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23,41,55,47,38])

In [22]:
#week with more than 40 hrs 
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [23]:
#week with hrs not equals to 40
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

##### Logical Operations

In [24]:
#Logical AND operation
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [26]:
#Logical NOT operation
np.logical_not(np_weekly_hrs>35)


array([ True, False, False, False, False])

In [28]:
#not using numpy
weeklydur = [23,41,55,47,38]
seldur = []
for i in weeklydur:
    if i>40:
        seldur.append(i)

In [29]:
print(seldur)

[41, 55, 47]


In [30]:
type(seldur)

list

In [33]:
#using lambda
seldur = list(map(lambda n: n*10,seldur))
#seldur = list(filter(lambda n: n>40,weeklydur))
#print(seldur)

In [34]:
seldur

[410, 550, 470]

In [35]:
seldur2 = list(filter(lambda n: n%235 == 0,seldur))

In [36]:
seldur2

[470]

In [37]:
def funct(x: int):
    if x%235 == 0:
        return x

In [40]:
funct(550)

In [42]:
seldur3 = list(map(lambda n: funct(n),seldur))

In [43]:
seldur3

[None, None, 470]