## __Arithmetic Operations in Python__

## Step 1: Arithmetic Operations using **NumPy**

Let's import the NumPy library: 

In [1]:
import numpy as np

In [2]:
test_scores = np.array([[78,98,100],[76,88,43]])

In [3]:
test_scores

array([[ 78,  98, 100],
       [ 76,  88,  43]])

In [4]:
test = test_scores > 43

In [11]:
test

array([[ True,  True,  True],
       [ True,  True, False]])

In [6]:
test1 = test_scores[test_scores > 70]

In [9]:
test1

array([ 78,  98, 100,  76,  88])

In [12]:
test_scores[test]

array([ 78,  98, 100,  76,  88])

In [26]:
countries = np.array(['germany','france','italy','finland','india','usa','australia',
'belgium','korea','japan','china','poland'])

In [27]:
countries2 = countries

In [28]:
countries == countries2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [29]:
np.insert(countries,1,'austria')

array(['germany', 'austria', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [30]:
countries

array(['germany', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [31]:
countries2

array(['germany', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [33]:
countries[0] = 'deutschland'

In [34]:
countries

array(['deutschla', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [35]:
countries2

array(['deutschla', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

Create two NumPy arrays using np.array():

In [37]:
countries3 = countries.view()

In [38]:
countries3 == countries

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [39]:
countries3 is countries

False

In [43]:
countries4 = countries[countries == 'italy']

In [45]:
countries5 = countries.copy()

In [46]:
countries5 is countries

False

In [47]:
countries


array(['Deutsch', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [48]:
countries[0] = 'Germany'

In [49]:
countries

array(['Germany', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [50]:
countries5

array(['Deutsch', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [41]:
countries

array(['Deutsch', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [42]:
countries3

array(['Deutsch', 'france', 'italy', 'finland', 'india', 'usa',
       'australia', 'belgium', 'korea', 'japan', 'china', 'poland'],
      dtype='<U9')

In [51]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

Display the arrays using their variable names:

In [53]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [56]:
B

array([3, 4, 5])

##Step 2: Addition
Now, perform element-wise addition of 'A' and 'B' using the 'np.add' method:

In [57]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

**Observation:**
- The result presented above is obtained by adding the two NumPy arrays.

##Step 3: Subtraction
Now, perform element-wise subtraction of 'A' from 'B' using the 'np.subtract' method:

In [ ]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

**Observation:**

- The result presented above is obtained by subtracting one of the NumPy arrays from the other.

##Step 4: Multiplication
Now, perform element-wise multiplication of 'A' and 'B' using the 'np.multiply' method:

In [ ]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

**Observation:**

- The result presented above is obtained by multiplying the two NumPy arrays.
- Remember, this multiplication is an element-wise multiplication not a matrix-type multiplication.

##Step 5. Division
- Now, perform element-wise division of 'A' by 'B' using the 'np.divide' method:

In [ ]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

**Observation:**

- The result presented above is obtained by dividing one of the NumPy arrays by the other.

##Step 6: Power Of
Now, let's raise one array to the power of '2' using the np.power() method:



In [ ]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]])

**Observation:**

- The result presented above shows the square of all the elements in the array.

Perform element-wise power operation where each element in 'A' is raised
to the corresponding element in 'B' using the 'np.power' method:

In [ ]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

**Observation:**

- The result presented above shows the NumPy array 'A' raised to the power of other array 'B'.