In [1]:
import numpy as np

## Problem 1

In [2]:
distance = [10,15,17,24]
time = [.30,.47,.55,1.20]

In [3]:
np_time = np.array(time)

In [5]:
for i in np_time:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [6]:
time2 = [100,.30,.47,.55,1.20]   
np_time2 = np.array(time2)

In [7]:
for i in np_time2:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [8]:
np_distance = np.array(distance)
speed = np_distance/np_time
print(speed)

[33.33333333 31.91489362 30.90909091 20.        ]


## Problem 2

In [9]:
first_trial_cyclist = [10,15,17,24]
second_trial_cyclist = [12,11,21,24]

In [10]:
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cylist = np.array(second_trial_cyclist)

In [11]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [12]:
print(result)

[22 26 38 48]


In [13]:
trials_new = np.array([first_trial_cyclist,second_trial_cyclist])

In [14]:
print(trials_new)

[[10 15 17 24]
 [12 11 21 24]]


In [15]:
trials_new.ndim

2

In [16]:
trials_new.dtype

dtype('int32')

In [17]:
trials_new[1:]

array([[12, 11, 21, 24]])

In [18]:
trials_new[:]

array([[10, 15, 17, 24],
       [12, 11, 21, 24]])

In [19]:
trials_new[:,0]

array([10, 12])

In [20]:
trials_new[:,1:3]

array([[15, 17],
       [11, 21]])

In [21]:
trials_new[:,1:3].shape

(2, 2)

In [22]:
for n in trials_new[1:]:
    for j in n:
         print(j,n)

12 [12 11 21 24]
11 [12 11 21 24]
21 [12 11 21 24]
24 [12 11 21 24]


In [23]:
for n in trials_new:
    print(n)

[10 15 17 24]
[12 11 21 24]


In [24]:
for n in trials_new:
    for j in n:
         print(j,n)

10 [10 15 17 24]
15 [10 15 17 24]
17 [10 15 17 24]
24 [10 15 17 24]
12 [12 11 21 24]
11 [12 11 21 24]
21 [12 11 21 24]
24 [12 11 21 24]


In [25]:
trials_sel = trials_new>17

In [26]:
print(trials_sel)

[[False False False  True]
 [False False  True  True]]


In [27]:
trials_self = trials_new[trials_sel]

In [28]:
trials_self

array([24, 21, 24])

## Broadcasting

In [3]:
import numpy as np
array_a = np.array([2,34,5,8])
array_b = np.array([.3,.3,.3,.3])

In [4]:
result = array_a * array_b
print(result)

[ 0.6 10.2  1.5  2.4]


In [5]:
#variable with a scalar value
scalar_c = 0.3

In [6]:
#multiple array with scalar value
result2 = array_a * scalar_c
print(result2)

[ 0.6 10.2  1.5  2.4]


## Problem 3

In [34]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA'])
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [35]:
#max gdp per capita (shows index position)
max_gdp_per_capita = gdp_per_capita.argmax()
print(max_gdp_per_capita)

0


In [36]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]
print(country_with_max_gdp_per_capita)

luxembourg


In [37]:
min_gdp_per_capital = gdp_per_capita.argmin()
print(min_gdp_per_capital)

3


In [38]:
country_with_min_gdp_per_capita = countries[min_gdp_per_capital]
print(country_with_min_gdp_per_capita)


Switzerland


In [39]:
#printing values iteratively
for country in countries:
    print('ecalculating country {}'.format(country))

ecalculating country luxembourg
ecalculating country Norway
ecalculating country Japan
ecalculating country Switzerland
ecalculating country USA


In [40]:
#using formating
for i in range(0,len(countries)-1):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {} per capita gdp is {}'.format(country,country_gdp_per_capita))

country luxembourg per capita gdp is 52056.1234
country Norway per capita gdp is 40345.4565
country Japan per capita gdp is 45456.78564
country Switzerland per capita gdp is 33245.56782


In [41]:
print(gdp_per_capita.max())
print(gdp_per_capita.min())
print(gdp_per_capita.mean())
print(gdp_per_capita.std())

52056.1234
33245.56782
41129.678448
6989.282898226141


In [7]:
#Using other functions
marks = np.array([[23,34,45,56],[23,23,34,67]])

In [8]:
marks

array([[23, 34, 45, 56],
       [23, 23, 34, 67]])

In [9]:
marks.transpose()

array([[23, 23],
       [34, 23],
       [45, 34],
       [56, 67]])

In [10]:
marks.reshape(4,2)

array([[23, 34],
       [45, 56],
       [23, 23],
       [34, 67]])

In [46]:
marks

array([[23, 34, 45, 56],
       [23, 23, 34, 67]])

In [47]:
from numpy import linalg
np.linalg.inv(marks)

LinAlgError: Last 2 dimensions of the array must be square

In [48]:
marks = np.array([[23,34],[23,23]])

In [49]:
from numpy import linalg
np.linalg.inv(marks)

array([[-0.09090909,  0.13438735],
       [ 0.09090909, -0.09090909]])

In [50]:
np.trace(marks)

46

## SciPy

In [1]:
import numpy as np
from scipy.integrate import quad

In [2]:
def integrateFunction(x):
    return x

In [3]:
quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [4]:
def integrateFn(x,a,b):
    return x*a+b

In [5]:
a = 3
b = 2

In [6]:
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [7]:
import scipy.integrate as integrate

In [9]:
def f(x,y):
    return x + y
    integrate.dblquad(f,0,1,lambda x: 0, lambda x:2)

In [10]:
f(0,2)

2

**Optimization**

In [12]:
import numpy as np
from scipy import optimize

In [13]:
def f(x):
    return x**2 + 5*np.sin(x)

In [15]:
minimaValue = optimize.minimize(f,x0=2,method='bfgs', options={'disp': True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [16]:
minimaValueWithoutOpt = optimize.minimize(f,x0=2,method='bfgs')

In [17]:
minimaValueWithoutOpt

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -3.2463942726915196
        x: [-1.111e+00]
      nit: 5
      jac: [-4.470e-07]
 hess_inv: [[ 1.545e-01]]
     nfev: 18
     njev: 9

__Another example

In [18]:
from scipy.optimize import root

In [19]:
def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [20]:
rootValue = root(rootfunc, 0.3)

In [21]:
rootValue

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [-1.216e+00]
    nfev: 14
    fjac: [[-1.000e+00]]
       r: [-4.282e+00]
     qtf: [-8.329e-13]

**linalg**

In [22]:
#Linear algebra
from scipy import linalg

In [24]:
matrix = np.array([[10,6],[2,7]])

In [25]:
matrix

array([[10,  6],
       [ 2,  7]])

In [26]:
type(matrix)

numpy.ndarray

In [27]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [28]:
matrix = np.array([[4,9],[3,5]])

In [30]:
linalg.det(matrix)

-6.999999999999999

In [31]:
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [32]:
numArrValue = np.array([21,9,6])

In [33]:
linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

__Another example

In [35]:
numSvdArr = np.array([[3,5,1],[9,5,7]])

In [36]:
numSvdArr.shape

(2, 3)

In [37]:
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

**Statistics**

In [38]:
from scipy.stats import norm

In [39]:
norm.rvs(loc=0,scale=1,size=10)

array([-0.8293302 , -0.66200263, -0.92709841,  2.15202888, -2.04392342,
        0.35101175, -0.01326101,  1.32203626,  1.13741918,  1.37192395])

In [40]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [41]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

In [42]:
#loc and scale are used to adjust the location and scale of the data distribution

In [44]:
import scipy.io as sio

In [50]:
mldata = sio.loadmat('../../Datasets/lena.mat')

In [51]:
type(mldata)

dict

In [52]:
mldata

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Wed Feb 20 11:29:14 2002',
 '__version__': '1.0',
 '__globals__': [],
 'lena512': array([[162, 162, 162, ..., 170, 155, 128],
        [162, 162, 162, ..., 170, 155, 128],
        [162, 162, 162, ..., 170, 155, 128],
        ...,
        [ 43,  43,  50, ..., 104, 100,  98],
        [ 44,  44,  55, ..., 104, 105, 108],
        [ 44,  44,  55, ..., 104, 105, 108]], dtype=uint8)}

In [53]:
lena_a = mldata['lena512']

In [54]:
lena_a

array([[162, 162, 162, ..., 170, 155, 128],
       [162, 162, 162, ..., 170, 155, 128],
       [162, 162, 162, ..., 170, 155, 128],
       ...,
       [ 43,  43,  50, ..., 104, 100,  98],
       [ 44,  44,  55, ..., 104, 105, 108],
       [ 44,  44,  55, ..., 104, 105, 108]], dtype=uint8)

In [55]:
lena_a.shape

(512, 512)

__Another example

In [63]:
vect = np.arange(10)

In [64]:
vect.shape

(10,)

In [65]:
sio.savemat('np_vector.mat', {'vect':vect})

In [66]:
vcdata = sio.loadmat('np_vector.mat')

In [67]:
vcdata

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Sep 18 07:58:33 2024',
 '__version__': '1.0',
 '__globals__': [],
 'vect': array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])}

In [70]:
vector_a = vcdata['vect']

In [71]:
vector_a.size

10

In [72]:
vector_a.shape

(1, 10)