In [13]:
def dot_product(x,y):
    return sum(i*j for i,j in zip(x,y,strict=True))

In [15]:
dot_product([1,2,3],[4,5,6])

32

In [9]:
#sum(1*4+2*5+3*6)

In [17]:
import numpy as np
x = np.array([1,2,3])

In [18]:
x

array([1, 2, 3])

In [19]:
y = np.array([100,200,300])

In [20]:
y

array([100, 200, 300])

In [21]:
res = zip(x,y)

In [23]:
for i in res:
    print(i)

(1, 100)
(2, 200)
(3, 300)


In [24]:
res2 = np.add(x,y)

In [25]:
res2

array([101, 202, 303])

In [26]:
res3 = np.subtract(y,x)

In [27]:
res3

array([ 99, 198, 297])

In [28]:
res4 = np.multiply(x,y)

In [29]:
res4

array([100, 400, 900])

In [33]:
def dot_product(x,y):
    return sum(i*j for i,j in zip(y,y))

In [34]:
dot_product([1,2,3],[4,5,6])

77

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.array([10,20,30])

In [6]:
b

array([10, 20, 30])

In [8]:
res = a+b

In [9]:
res

array([[11, 22, 33],
       [14, 25, 36]])

In [10]:
res2 = np.add(a,b)

In [11]:
res2

array([[11, 22, 33],
       [14, 25, 36]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c = 20

In [14]:
a*c

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [15]:
def myfunc(s,m):
    sm = m
    for i in range(len(m)):
        for j in range(len(m[0])):
            sm[i][j] = s*sm[i][j]
    return sm

In [19]:
myfunc(1000,a)

array([[100000, 200000, 300000],
       [400000, 500000, 600000]])

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
10+a,10*a,10-a,a+a,a*a

(array([[11, 12, 13],
        [14, 15, 16]]),
 array([[10, 20, 30],
        [40, 50, 60]]),
 array([[9, 8, 7],
        [6, 5, 4]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]),
 array([[ 1,  4,  9],
        [16, 25, 36]]))

In [9]:
b = np.array([[1,4,1],[1,2,6]])

In [10]:
b

array([[1, 4, 1],
       [1, 2, 6]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b*a

array([[ 1,  8,  3],
       [ 4, 10, 36]])

In [24]:
a = np.array([[1,2,3],[4,5,6]])

In [25]:
b = np.array([[1,2],[3,4],[5,6]])

In [26]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [27]:
res = np.matmul(a,b)

In [28]:
res


array([[22, 28],
       [49, 64]])

In [31]:
x = np.loadtxt('Sample_File.csv',delimiter=',',dtype='str')

In [32]:
x

array([['Name', 'age', 'gender'],
       ['john', '20', 'male'],
       ['peter', '40', 'male'],
       ['marie', '30', 'female']], dtype='<U6')

In [33]:
x[0]

array(['Name', 'age', 'gender'], dtype='<U6')

In [41]:
x

array([['Name', 'age', 'gender'],
       ['john', '20', 'male'],
       ['peter', '40', 'male'],
       ['marie', '30', 'female']], dtype='<U6')

In [45]:
type(x)

numpy.ndarray

In [46]:
x

array([['Name', 'age', 'gender'],
       ['john', '20', 'male'],
       ['peter', '40', 'male'],
       ['marie', '30', 'female']], dtype='<U6')

In [48]:
transposedx = np.transpose(x)

In [50]:
transposedx

array([['Name', 'john', 'peter', 'marie'],
       ['age', '20', '40', '30'],
       ['gender', 'male', 'male', 'female']], dtype='<U6')

In [68]:
x[0]

array(['Name', 'age', 'gender'], dtype='<U6')

In [69]:
x.T[0]

array(['Name', 'john', 'peter', 'marie'], dtype='<U6')

In [70]:
x

array([['Name', 'age', 'gender'],
       ['john', '20', 'male'],
       ['peter', '40', 'male'],
       ['marie', '30', 'female']], dtype='<U6')

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6]])