In [ ]:
import datetime

In [ ]:
from datetime import date
mydate = date(2023,11,26)

In [ ]:
print(type(mydate))


In [ ]:
mydate = '2023-11-26'

In [ ]:
x = datetime.strptime(mydate, "%Y-%m-%d")

In [ ]:
x.year

In [ ]:
x.month

In [ ]:
x.day

In [ ]:
mydate = date(2023,12,27)

In [ ]:
mydate.year

In [ ]:
mydate.month

In [ ]:
mydate.day

In [ ]:
today = datetime.now()

In [ ]:
today

In [ ]:
from datetime import timedelta
futdate = today + timedelta(days=10)

In [ ]:
futdate

In [ ]:
difference = futdate - today

In [ ]:
difference

In [ ]:
calcnow = today.toordinal() - futdate.toordinal()

In [ ]:
calcnow

In [ ]:
import calendar

In [ ]:
date

In [ ]:
mydate = date(2023,12,27)

In [ ]:
mydate.month

In [ ]:
mydate.day

In [67]:
calendar.weekday(mydate.year,mydate.month,mydate.day)

2

In [68]:
mydates = ['2023-11-1','2023-11-2','2023-11-3','2023-11-4','2023-11-5','2023-11-6','2023-11-7','2023-11-8']

In [69]:
#populate values in these empty lists
monthval = []
dayval = []
yearval = []
weekdays = []

In [70]:
#monthval.append()

In [73]:
for i in mydates:
    print(i,type(i))

2023-11-1 <class 'str'>
2023-11-2 <class 'str'>
2023-11-3 <class 'str'>
2023-11-4 <class 'str'>
2023-11-5 <class 'str'>
2023-11-6 <class 'str'>
2023-11-7 <class 'str'>
2023-11-8 <class 'str'>


In [80]:
monthval = list(map(lambda n: (datetime.strptime(n, "%Y-%m-%d").month),mydates))
yearval = list(map(lambda n: (datetime.strptime(n, "%Y-%m-%d").year),mydates))
dayval = list(map(lambda n: (datetime.strptime(n, "%Y-%m-%d").day),mydates))

In [79]:
monthval

[11, 11, 11, 11, 11, 11, 11, 11]

In [81]:
yearval

[2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023]

In [82]:
dayval

[1, 2, 3, 4, 5, 6, 7, 8]

In [91]:

   #using Pandas (suggested by Arka)
import pandas as pd
mydates=['11-12-2023','12-12-2023']

months_val=[]
days_val=[]
year_val=[]
weekdays=[]
for i in mydates:

    date_pd=pd.Timestamp(i)
    months_val.append(date_pd.month_name())
    days_val.append(date_pd.day)
    year_val.append(date_pd.year)
    weekdays.append(date_pd.day_name())
print(months_val)
print(days_val)
print(year_val)
print(weekdays)


['November', 'December']
[12, 12]
[2023, 2023]
['Sunday', 'Tuesday']


In [103]:
greetings = ['hello','hi','welcome','namste','bonjour']

In [104]:
chogre = [n for n in greetings if len(n)>2 ]

In [105]:
chogre

['hello', 'welcome', 'namste', 'bonjour']

In [109]:
chogre = [n for n in greetings if n[0] == 'h' ]

In [110]:
chogre

['hello', 'hi']

In [111]:
chogrelam = list(filter(lambda n: n[0]=='h',greetings))

In [112]:
chogrelam

['hello', 'hi']

In [119]:
x = '15S'

In [115]:
def timeff(x):
    n = pd.to_timedelta(x)
    return n

In [120]:
timeff(x)

Timedelta('0 days 00:00:15')

In [121]:
mytime = ['1H15M','15M','15M30S']

In [123]:
for i in mytime:
    print(timeff(i))

0 days 01:15:00
0 days 00:15:00
0 days 00:15:30


/tmp/ipykernel_70/125088881.py:2: FutureWarning: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and will be removed in a future version.
  n = pd.to_timedelta(x)


In [124]:
import numpy as np

In [125]:
for i in mytime:
    print(timeff(i)/np.timedelta64(1, 'm'))

75.0
15.0
15.5


/tmp/ipykernel_70/125088881.py:2: FutureWarning: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and will be removed in a future version.
  n = pd.to_timedelta(x)


In [126]:
x = np.array(range(1,10))


In [127]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
type(x)

numpy.ndarray

In [131]:
x.ndim

1

In [132]:
x.shape

(9,)

In [133]:
x.size

9

In [135]:
x.max()

9

In [136]:
y = range(1,10)
type(y)

range

In [137]:
y = np.array(range(1,10))
type(y)

numpy.ndarray

In [138]:
y = list(range(1,10))
type(y)

list

In [140]:
y = np.array(range(1,10))

In [143]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [146]:
df1.columns

Index(['key', 'data1'], dtype='object')

In [151]:
df1['key'] = df1['key'].apply(lambda n:n.upper())

In [152]:
df1

key  data1
0   B      0
1   B      1
2   A      2
3   C      3
4   A      4
5   A      5
6   B      6

In [153]:
df2 = pd.DataFrame({'population': [20000,40000,50000,100000,500000],'countries': ['germany','italy','america','china','india']})

In [154]:
df2

population countries
0       20000   germany
1       40000     italy
2       50000   america
3      100000     china
4      500000     india

In [155]:
df2.iloc(1)

In [1]:
#Dec22023

In [2]:
list = [10,20,45.4,35,2223.3333]

In [3]:
type(list)

list

In [4]:
list = ['welcome',23,23,4,'hello']

In [5]:
type(list)

list

In [6]:
for i in list:
    print(i,type(i))

welcome <class 'str'>
23 <class 'int'>
23 <class 'int'>
4 <class 'int'>
hello <class 'str'>


In [7]:
set1 = (1,2,2,3,2,3,4,4)

In [8]:
type(set1)

tuple

In [9]:
actset = set(set1)

In [10]:
type(actset)

set

In [11]:
actset

{1, 2, 3, 4}

In [12]:
dict = ({1:'welcome'},{2:'hello'})

In [13]:
type(dict)

tuple

In [16]:
import numpy as np

In [17]:
list

['welcome', 23, 23, 4, 'hello']

In [18]:
tryconv = np.array(list)

In [19]:
type(tryconv)

numpy.ndarray

In [20]:
for i in tryconv:
    print(i,type(i))

welcome <class 'numpy.str_'>
23 <class 'numpy.str_'>
23 <class 'numpy.str_'>
4 <class 'numpy.str_'>
hello <class 'numpy.str_'>


In [21]:
for i in tryconv:
    print(i,i*100)

welcome welcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcomewelcome
23 23232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323232323
23 232323232323232323232323232323232323232323232323232323232323232323232323232323232323

In [22]:
tryconv


array(['welcome', '23', '23', '4', 'hello'], dtype='<U21')

In [24]:
tryconv.ndim

1

In [25]:
tryconv.shape


(5,)

In [26]:
tryconv.size

5

In [27]:
tryconv.dtype

dtype('<U21')

In [28]:
tryconv.itemsize

84

In [30]:
tryconv.reshape(5,1)

array([['welcome'],
       ['23'],
       ['23'],
       ['4'],
       ['hello']], dtype='<U21')

In [31]:
tryconv

array(['welcome', '23', '23', '4', 'hello'], dtype='<U21')

In [32]:
n = tryconv.reshape(5,1)

In [33]:
n.shape

(5, 1)

In [35]:
tryconv.shape

(5,)

In [36]:
tryconv.size

5

In [38]:
n.size

5

In [39]:
listoflist = [[1,2,3],[3,4,5],[4,5,6]]

In [40]:
type(listoflist)

list

In [41]:
for i in listoflist:
    print(i,type(i))

[1, 2, 3] <class 'list'>
[3, 4, 5] <class 'list'>
[4, 5, 6] <class 'list'>


In [44]:
for i in listoflist:
    for j in i:
        print(i,j,'this is type of element: ',type(i),'this is type of element in element:', type(j))

[1, 2, 3] 1 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[1, 2, 3] 2 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[1, 2, 3] 3 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[3, 4, 5] 3 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[3, 4, 5] 4 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[3, 4, 5] 5 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[4, 5, 6] 4 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[4, 5, 6] 5 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>
[4, 5, 6] 6 this is type of element:  <class 'list'> this is type of element in element: <class 'int'>


In [45]:
arr = np.array(listoflist)

In [46]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [49]:
for i in arr:
    for j in i:
        print(i,j,type(j))

[1 2 3] 1 <class 'numpy.int64'>
[1 2 3] 2 <class 'numpy.int64'>
[1 2 3] 3 <class 'numpy.int64'>
[3 4 5] 3 <class 'numpy.int64'>
[3 4 5] 4 <class 'numpy.int64'>
[3 4 5] 5 <class 'numpy.int64'>
[4 5 6] 4 <class 'numpy.int64'>
[4 5 6] 5 <class 'numpy.int64'>
[4 5 6] 6 <class 'numpy.int64'>


In [50]:
listoflist2 = [[1,2,3.5],['hello','welcome','cool']]

In [51]:
arr = np.array(listoflist2)

In [52]:
arr

array([['1', '2', '3.5'],
       ['hello', 'welcome', 'cool']], dtype='<U32')

In [53]:
for i in arr:
    for j in i:
        print(i,j,type(j))

['1' '2' '3.5'] 1 <class 'numpy.str_'>
['1' '2' '3.5'] 2 <class 'numpy.str_'>
['1' '2' '3.5'] 3.5 <class 'numpy.str_'>
['hello' 'welcome' 'cool'] hello <class 'numpy.str_'>
['hello' 'welcome' 'cool'] welcome <class 'numpy.str_'>
['hello' 'welcome' 'cool'] cool <class 'numpy.str_'>


In [54]:
arr.ndim

2

In [55]:
arr.size

6

In [56]:
arr.shape

(2, 3)

In [57]:
arr.itemsize

128

In [2]:
import numpy as np


In [7]:
auctiondata = np.loadtxt('auction.csv',delimiter=',',dtype='str')

In [8]:
auctiondata

array([['auctionid', 'bid', 'bidtime', ..., 'price', 'item',
        'auction_type'],
       ['1638893549', '175', '2.230949', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ['1638893549', '100', '2.600116', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ...,
       ['8214889177', '90', '6.428738', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '88', '6.760081', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '90.01', '6.988831', ..., '90.01',
        'Xbox game console', '7 day auction']], dtype='<U33')

In [9]:
auctiondata.size

96138

In [10]:
auctiondata.ndim

2

In [11]:
auctiondata.shape

(10682, 9)

In [12]:
auctiondata[0]

array(['auctionid', 'bid', 'bidtime', 'bidder', 'bidderrate', 'openbid',
       'price', 'item', 'auction_type'], dtype='<U33')

In [13]:
auctiondata[0:2]

array([['auctionid', 'bid', 'bidtime', 'bidder', 'bidderrate', 'openbid',
        'price', 'item', 'auction_type'],
       ['1638893549', '175', '2.230949', 'schadenfreud', '0', '99',
        '177.5', 'Cartier wristwatch', '3 day auction']], dtype='<U33')

In [21]:
auctiondata

array([['auctionid', 'bid', 'bidtime', ..., 'price', 'item',
        'auction_type'],
       ['1638893549', '175', '2.230949', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ['1638893549', '100', '2.600116', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ...,
       ['8214889177', '90', '6.428738', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '88', '6.760081', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '90.01', '6.988831', ..., '90.01',
        'Xbox game console', '7 day auction']], dtype='<U33')

In [19]:
popdata

array([['auctionid', 'bid', 'bidtime', ..., 'price', 'item',
        'auction_type'],
       ['1638893549', '175', '2.230949', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ['1638893549', '100', '2.600116', ..., '177.5',
        'Cartier wristwatch', '3 day auction'],
       ...,
       ['8214889177', '90', '6.428738', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '88', '6.760081', ..., '90.01',
        'Xbox game console', '7 day auction'],
       ['8214889177', '90.01', '6.988831', ..., '90.01',
        'Xbox game console', '7 day auction']], dtype='<U33')

In [23]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [26]:
collective_data = new_cyclist_trials.ravel()

In [30]:
print(np.hsplit(collective_data,4))

[array([10, 15, 17]), array([26, 13, 19]), array([12, 13, 14]), array([24, 14, 23])]


In [31]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA'])

In [32]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA'],
      dtype='<U11')

In [33]:
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [35]:
gdp_per_capita

array([52056.1234 , 40345.4565 , 45456.78564, 33245.56782, 34544.45888])

In [41]:
max_gdp_per_capita = gdp_per_capita.max()

In [42]:
max_gdp_per_capita

52056.1234

In [43]:
max_gdp_per_capita = gdp_per_capita.argmax()

In [44]:
max_gdp_per_capita

0

In [45]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]

In [46]:
country_with_max_gdp_per_capita

'luxembourg'

In [47]:
for i in range(0,len(countries)-1):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {} per capita gdp is {}'.format(country,country_gdp_per_capita))


country luxembourg per capita gdp is 52056.1234
country Norway per capita gdp is 40345.4565
country Japan per capita gdp is 45456.78564
country Switzerland per capita gdp is 33245.56782
