##__NumPy Array Shapes and Axes__##

## Step 1: Creating NumPy Arrays

- Create multiple dimensional arrays, such as 1D, 2D and 3D
- Print the dimension and shapes of those NumPy arrays


Let's first import the NumPy package:

In [2]:
import numpy as np

## Step 2: Create a 0D Array
- Use the dot array method
- Pass a scalar value to it, such as 24

In [3]:
np.array(24)

array(24)

In [10]:
x = np.array([24])
x.shape

(1,)

**Observation:**
- 0D arrays are scalars where each scalar value can be considered an element of the array, such as 24. 

## Step 3: Creating a 1D Array
- 1D arrays are unidimensional and have 0D arrays as its elements.



Let's create a 1D array:

In [11]:
#first NumPy arrayp
first_numpy_array = np.array([1,2,3,4])

In [12]:
#print first array
print(first_numpy_array)

[1 2 3 4]


##Step 4: Creating a 2D Array
- 2D arrays have 1D arrays as their elements.
- They are also called 2nd order tensors.
- They are often used to represent matrices.

Let's create a 2D array:

In [13]:
TwoD_array_ex1 = np.array([[1,1,1],[1,2,1]])

In [14]:
print(TwoD_array_ex1)

[[1 1 1]
 [1 2 1]]


In [22]:
TwoD_array_ex1.size,TwoD_array_ex1.ndim,TwoD_array_ex1.shape,TwoD_array_ex1.dtype

(6, 2, (2, 3), dtype('int32'))

In [23]:
_

(6, 2, (2, 3), dtype('int32'))

## Step 5: Creating a 3D Array
- 3D arrays have 2D arrays as their elements.

In [20]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

##Step 6: Checking the Dimension and Shape of an Array


Let's create a 3-D array using np.array():

In [24]:
numpy_arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

Now, display the shape of the array using .shape:

In [25]:
numpy_arr.shape

(2, 2, 3)

**Observation:**
- The shape of a 3D array is (2, 2, 3).


Then, display the number of dimensions in the array using .ndim:

In [26]:
numpy_arr.ndim

3

**Observation:**
- The array is a three-dimensional array.


In [35]:
numpy_arr[1][1:]

array([[4, 4, 4]])

##Step 7. Creating an Array with a Desired Number of Dimensions


Let's create a five-dimensional NumPy array using the **ndmin** parameter:

In [36]:
np.array([1,2,3,4,5],ndmin = 5)

array([[[[[1, 2, 3, 4, 5]]]]])

Now, print the number of dimensions of the array mentioned in above cell:

In [37]:
array= np.array([1,2,3,4,5],ndmin = 5)
array.ndim

5

In [53]:
#array[:][0] --to verify

In [47]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
print(array_with_ones.shape,
array_with_ones.size,
array_with_ones.dtype,
array_with_ones.ndim)

(3, 3) 9 float64 2


In [50]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
x = range(1,10)

In [57]:
for i in x:
    print(i,end=',')

1,2,3,4,5,6,7,8,9,

In [60]:
y = range(1,10,2)

In [61]:
for i in y:
    print(i,end=',')

1,3,5,7,9,

In [62]:
test = [(2,4),(4,5)]

In [68]:
l = []
for i in test:
    l.append(range(i[0],i[1]))

In [69]:
l

[range(2, 4), range(4, 5)]

In [70]:
#array with arange method
np_arange = np.arange(12)

In [18]:
#print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
np_arange.ndim

1

In [72]:
#reshape method to change/ create array
np_arange.reshape(3,4)
#print(np_arange.reshape(4,3))
#print(np_arange.reshape(3,4))
#print(np_arange.reshape(6,2))
#print(np_arange.reshape(2,6))
#print(np_arange.reshape(1,12))
#print(np_arange.reshape(12,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
#linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)

In [79]:
#print linespaced array
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [22]:
#One dimensional array
oneD_array = np.arange(15)

In [23]:
#print 1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [24]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)

In [25]:
#print 2D array
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
#Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)

In [27]:
#Print 3D array
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
