In [9]:

#countries = a 3*2*2 matrix (ndim array) with country names
#times - 1D2H 2H30M 30M1S 
import numpy as np
countries = ['germany','france','italy','finland','india','usa','australia','belgium','korea','japan','china','poland']

In [25]:
list_of_countries = np.array(countries).reshape(3,2,2)

In [29]:
list_of_countries

array([[['germany', 'france'],
        ['italy', 'finland']],

       [['india', 'usa'],
        ['australia', 'belgium']],

       [['korea', 'japan'],
        ['china', 'poland']]], dtype='<U9')

In [33]:
#list_of_countries[:]
list_of_countries[:][1][0]

array(['india', 'usa'], dtype='<U9')

In [17]:
for i in list_of_countries[:][1][0]:
    print(i[0:2])

in
us


In [37]:
list_of_countries2 = np.array(countries).reshape(2,2,-1)

In [39]:
list_of_countries2

array([[['germany', 'france', 'italy'],
        ['finland', 'india', 'usa']],

       [['australia', 'belgium', 'korea'],
        ['japan', 'china', 'poland']]], dtype='<U9')

## __NumPy Array Shapes and Axes__

In the previous file, we learned how to create 0D, 1D, 2D and 3D arrays.  Here, we will learn to convert one form of array to another. 

## Step 1: Converting a 1D Array to a 2D Array

Let's first create a 1D array:


In [34]:
import numpy as np
numpy_arr = np.array([x for x in range(1,10)])

Now, display the 1D array:

In [35]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Then, reshape the 1D array into a 2D array with shape **(3,3)**:
- The .reshape() method is used to convert one form of array into another.

In [36]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Observation:**
- In this case, the desired array has the shape (3,3), and this shape is being passed as a parameter in the method.

## Step 2: Converting a 1D Array to a 3D Array


Let's create a 1D array:

In [ ]:
numpy_arr = np.array([x for x in range(1,13)])

Then, reshape this 1D array into a 3D array with the shape (2,2,3):

In [ ]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

It is also possible to change the shape of this array according to our desired specifications.
- Reshape the 1D array used above into a 3D array with the shape (3,2,2):

In [ ]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

**Observation:**
- The shape of the array has been changed from (2,2,3) to (3,2,2).
- Remember that the length of the 1D array must be equal to the product of the 3D array.
- In this case, the length of the 1D array is 12 and the product of the 3D array is also 12 (2$*$2$*$3) or 12 (3$*$2$*$2).


- If the above condition is not satisfied, an error will occur.

##Step 3: Reshaping Arrays Without Specifying a New Shape
- Dealing with a large set of Pandas DataFrames can be challenging at times.
- If NumPy is being used, the function can be reshaped into an unknown dimension in that case.

Let's take an example:
- Take the 3D array used in step 2 and pass -1 as the value, and NumPy will calculate this number.

In [ ]:
numpy_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**Observation:**
- The unknown dimension has been calculated automatically by NumPy.

##Step 4: Flattening the arrays
- Now, we will start by converting a multidimensional array into a 1D array. 

Take the 3D array used in **Step 2** and convert it to a 1D array
- Assign a variable name to the 3D array as shown below:

In [ ]:
numpy_arr = numpy_arr.reshape(3,2,2)

Then, display the 3D array:

In [ ]:
numpy_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Finally, reshape the 3D array into a 1D array:

In [ ]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:

new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [41]:
new_cyclist_trials.ndim

2

In [42]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [43]:
#using ravel() to get altogether
x = new_cyclist_trials.ravel()

In [44]:
x.ndim

1

In [45]:
x

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [46]:
y = new_cyclist_trials.reshape(3,4)

In [50]:
y.ndim

2

In [10]:
y

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [48]:
new_cyclist_trials.resize(6,2)

In [49]:
new_cyclist_trials.ndim

2

In [13]:
new_cyclist_trials.shape

(6, 2)

In [14]:
#flatten the dataset
print(new_cyclist_trials.ravel())

[10 15 17 26 13 19 12 13 14 24 14 23]


In [51]:
#split array into 2
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [52]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [19]:
print(np.hsplit(new_cyclist_trials,2))

[array([[10, 15, 17],
       [12, 13, 14]]), array([[26, 13, 19],
       [24, 14, 23]])]


In [20]:
new_cyclist_1 = [10,15,17,26,13,19]
new_cyclist_2 = [12,13,14,24,14,23]

In [21]:
#stack the arrays together
print(np.hstack([new_cyclist_1,new_cyclist_2]))

[10 15 17 26 13 19 12 13 14 24 14 23]
