In [1]:
#Testing with existing data of Mogreps-UK
sample_sns_message = {
    
    'bucket': 'awsbigdatatakehome',
    'key': 'prods_op_mogreps-uk_20140717_03_11_015.nc'
}

In [2]:
#function to download data from s3
import urllib.request
import iris

def download_data_object(sns_message):
    url = "https://s3.eu-west-2.amazonaws.com/" + sns_message['bucket'] + "/" + sns_message['key']
    urllib.request.urlretrieve(url, sns_message['key']) 


In [3]:
#download the file
download_data_object(sample_sns_message)

In [4]:
filename='prods_op_mogreps-uk_20140717_03_11_015.nc'

In [5]:
#Loading list of cubes from the file
listofcubes = iris.load(filename)

In [6]:
print(listofcubes)

0: cloud_base_altitude_assuming_only_consider_cloud_area_fraction_greater_than_2p5_oktas / (kft) (time: 3; grid_latitude: 548; grid_longitude: 421)
1: stratiform_snowfall_rate / (kg m-2 s-1) (time: 36; grid_latitude: 548; grid_longitude: 421)
2: wet_bulb_freezing_level_altitude / (m) (time: 3; grid_latitude: 548; grid_longitude: 421)
3: wet_bulb_potential_temperature / (K) (time: 3; pressure: 3; grid_latitude: 548; grid_longitude: 421)
4: unknown / (1)                       (time: 3; grid_latitude: 548; grid_longitude: 421)
5: cloud_area_fraction_assuming_maximum_random_overlap / (1) (time: 3; grid_latitude: 548; grid_longitude: 421)
6: air_pressure_at_sea_level / (Pa)    (time: 3; grid_latitude: 548; grid_longitude: 421)
7: air_temperature / (K)               (time: 3; pressure: 2; grid_latitude: 548; grid_longitude: 421)
8: air_temperature / (K)               (time: 3; grid_latitude: 548; grid_longitude: 421)
9: air_temperature / (K)               (time: 3; grid_latitude: 548; grid_l

In [7]:
#Extract one cube, air_temperature measure in Kelvin. 
cube=listofcubes[8]

In [8]:
print(cube)

air_temperature / (K)               (time: 3; grid_latitude: 548; grid_longitude: 421)
     Dimension coordinates:
          time                           x                 -                    -
          grid_latitude                  -                 x                    -
          grid_longitude                 -                 -                    x
     Auxiliary coordinates:
          forecast_period                x                 -                    -
     Scalar coordinates:
          forecast_reference_time: 2014-07-17 03:00:00
          height: 1.5 m
     Attributes:
          Conventions: CF-1.5
          STASH: m01s03i236
          source: Data from Met Office Unified Model
          um_version: 8.5


In [12]:
#Number of dimensions for time coordinate
cube.coord('time').points.size


3

In [13]:
#Looking at dimensions for the time coordinate
cube.coord('time').points

array([390448., 390449., 390450.])

In [14]:
#Number of dimensions for the longitude coordinate
cube.coord('grid_longitude').points.size

421

In [15]:
#looking at longitute coordinates
grid_longitude = cube.coord('grid_longitude').points

In [16]:
grid_longitude[0:10]

array([354.91074, 354.93073, 354.95074, 354.97073, 354.99072, 355.01074,
       355.03073, 355.05075, 355.07074, 355.09073], dtype=float32)

In [17]:
#Number of dimensions for the latitude coordinate
cube.coord('grid_latitude').points.size

548

In [18]:
#looking at latitude coordinates
grid_latitude = cube.coord('grid_latitude').points

In [19]:
grid_latitude[0:10]

array([-3.77995  , -3.75995  , -3.73995  , -3.71995  , -3.69995  ,
       -3.67995  , -3.65995  , -3.6399498, -3.6199498, -3.5999498],
      dtype=float32)

In [20]:
#Convert from kelvin to Celsius
cube.convert_units('celsius')


In [21]:
#Print the cube contents
print(cube.data)


[[[16.35  16.35  16.35  ... 30.975 31.1   30.975]
  [16.35  16.35  16.35  ... 30.975 30.85  30.475]
  [16.35  16.35  16.35  ... 30.725 30.6   30.1  ]
  ...
  [14.1   14.1   14.1   ... 15.975 15.975 15.975]
  [14.1   14.1   14.1   ... 15.85  15.85  15.975]
  [14.1   14.1   14.1   ... 15.85  15.975 15.975]]

 [[16.35  16.35  16.35  ... 30.6   30.725 30.6  ]
  [16.35  16.35  16.35  ... 30.6   30.6   30.1  ]
  [16.35  16.35  16.35  ... 30.475 30.225 29.725]
  ...
  [14.225 14.225 14.225 ... 15.975 15.975 16.1  ]
  [14.225 14.225 14.225 ... 15.975 16.1   16.1  ]
  [14.1   14.1   14.225 ... 16.1   16.1   15.975]]

 [[16.225 16.225 16.225 ... 29.225 29.475 29.475]
  [16.225 16.225 16.225 ... 29.475 29.35  28.725]
  [16.225 16.225 16.225 ... 29.475 29.1   28.475]
  ...
  [14.225 14.225 14.225 ... 15.85  15.975 15.975]
  [14.225 14.225 14.225 ... 15.975 15.975 15.975]
  [14.225 14.225 14.225 ... 15.975 15.975 15.975]]]


In [22]:
#Get a subset of the data
print(cube.data[0])


[[16.35  16.35  16.35  ... 30.975 31.1   30.975]
 [16.35  16.35  16.35  ... 30.975 30.85  30.475]
 [16.35  16.35  16.35  ... 30.725 30.6   30.1  ]
 ...
 [14.1   14.1   14.1   ... 15.975 15.975 15.975]
 [14.1   14.1   14.1   ... 15.85  15.85  15.975]
 [14.1   14.1   14.1   ... 15.85  15.975 15.975]]


In [23]:
#Other information 
cube.shape

(3, 548, 421)

In [24]:
cube.ndim

3

In [25]:
type(cube.data)

numpy.ma.core.MaskedArray

In [26]:
cube.standard_name

'air_temperature'

In [28]:
cube.long_name
cube.var_name

'air_temperature'

In [29]:
cube.units

Unit('celsius')

In [30]:
cube.data.max()

33.35

In [31]:
cube.attributes

{'source': 'Data from Met Office Unified Model',
 'um_version': '8.5',
 'Conventions': 'CF-1.5',
 'STASH': STASH(model=1, section=3, item=236)}